### ISSUE TITLE
Improve error for account not found

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-cli#560] opened 2020-10-01 17:58 UTC
Current error for account not found is misleading and too verbose

**Comment by june07** [comment] 2020-10-02 18:38
> The account you provided [ yadayada.testnet ] does not exist on the [ default ] network (using https://rpc.testnet.near.org)

Is that what you are referring to?

**Comment by luciotato** [comment] 2020-10-08 08:38
you want to change:
```
> near keys llss
An error occured
{ Error: [-32000] Server error: account llss does not exist while viewing
    at JsonRpcProvider.sendJsonRpc (/usr/local/lib/node_modules/near-cli/node_modules/near-api-js/lib/providers/json-rpc-provider.js:158:27)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  [stack]:
   'Error: [-32000] Server error: account llss does not exist while viewing\n    at JsonRpcProvider.sendJsonRpc (/usr/local/lib/node_modules/near-cli/node_modules/near-api-js/lib/providers/json-rpc-provider.js:158:27)\n    at process._tickCallback (internal/process/next_tick.js:68:7)',
  [message]:
   '[-32000] Server error: account llss does not exist while viewing',
  type: 'UntypedError',
  context: undefined }

```
to
```
> near keys llss
ERR: Account 'llss' does not exists on testnet
```

?

**Comment by volovyk-s** [comment] 2020-11-17 08:59
@ilblackdragon looks like this issue is a duplicate of https://github.com/near/near-cli/issues/530

**Comment by volovyk-s** [comment] 2020-11-30 16:07
Closed a duplicate of https://github.com/near/near-cli/issues/530

**Closed by volovyk-s** 2020-11-30 16:07 UTC
