### ISSUE TITLE
When adding a key on mainnet, the link to transaction leads to testnet explorer

### ISSUE THREAD

**Issue by SkidanovAlex** [near/near-cli#586] opened 2020-10-27 20:54 UTC
**Describe the bug**

```
(.env) $ near add-key alex.near 5WkR9VcE7s4wUpp7kQwMN6ip1PT7W96Zth2a7akapbaU --accountId=alex.near --networkId=mainnet --nodeUrl=https://rpc.mainnet.near.org
Adding full access key = 5WkR9VcE7s4wUpp7kQwMN6ip1PT7W96Zth2a7akapbaU to alex.near.
Transaction Id FAi3U6vjGCw4KoG7bWo3q4PHf7WyMjz9VvSVjoRXUuBy
To see the transaction in the transaction explorer, please open this url in your browser
https://explorer.testnet.near.org/transactions/FAi3U6vjGCw4KoG7bWo3q4PHf7WyMjz9VvSVjoRXUuBy
```

Note that the link to the transaction is to the `testnet` explorer, while the transaction indeed appeared on mainnet, and the key was successfully added.

**Expected behavior**
The link should be to the mainnet explorer

**Additional context**
Freshly installed from `npm`

```
$ near --version
1.2.0
```

**Comment by thisisjoshford** [comment] 2021-05-21 04:40
This looks like another issue with `--networkId` flag being used incorrectly as previously discussed in paused issue https://github.com/near/near-cli/issues/394 @mikedotexe. The transaction link is constructed based on the `networkId` defined in `NEAR_ENV` or `NODE_ENV` not `--networkId`. This command was completed successfully on `mainnet` as the `--nodeUrl` flag was used overriding the .env network config.

**Comment by thisisjoshford** [comment] 2021-05-21 04:49
Yep, just confirmed that this was the case by adding a key to a mainnet account and getting a mainnet link @mikedotexe @SkidanovAlex.

```bash
Adding full access key = 6LKUTeubEcJkbXQuHUhPpWN8kvbwRyMTkHpBVJhZ9Uy5 to example.near.
Transaction Id 7VDtjqFR2uwCRTvYxhvE7LynH2onLyrjt2KgVqmxUTHw
To see the transaction in the transaction explorer, please open this url in your browser
https://explorer.mainnet.near.org/transactions/7VDtjqFR2uwCRTvYxhvE7LynH2onLyrjt2KgVqmxUTHw
```

Closing this issue but may want to reconsider pausing https://github.com/near/near-cli/issues/394 as I think people will continue to confuse the functionality of the `--networkId` flag.

**Closed by thisisjoshford** 2021-05-21 04:49 UTC
Labels: bug
