### ISSUE TITLE
near-shell only allows creating subaccounts

### ISSUE THREAD

**Issue by nearmax** [near/near-cli#491] opened 2020-08-08 00:04 UTC
When entering this command:
```bash
near create-account alice007.testnet --masterAccount bridge03.testnet
```
I am getting this error message:
```bash
New account doesn't share the same top-level account. Expecting account name to end in ".bridge03.testnet"
```
There is no reason to have this restriction in near-shell since near-api-js does not have it.

**Comment by vgrichina** [comment] 2020-08-08 00:46
@nearmax aren't we supposed to have this restriction in nearcore though?

**Comment by bowenwang1996** [comment] 2020-08-08 02:41
@nearmax this is not allowed on the protocol level

**Comment by mikedotexe** [comment] 2020-08-12 23:06
I believe this is working as intended. We added this check to help explain to people why they are not allowed to do this action. Getting an error from the RPC is _suboptimal_ so this was added. May I close this, @nearmax or are you still concerend?

**Comment by mikedotexe** [comment] 2020-08-12 23:08
I should add, you are also allowed to create a TLA if it's >= 32 characters. I believe there is discussion to increase this size, and we'll increase it at that time. Again, the main reason we have this messaging is to inform users.

**Comment by mikedotexe** [comment] 2021-03-19 15:23
Closing as I believe this is addressed

**Closed by mikedotexe** 2021-03-19 15:23 UTC
Labels: bug
