### ISSUE TITLE
SIGSEGV error when using Ledger

### ISSUE THREAD

**Issue by volovyk-s** [near/near-cli#762] opened 2021-05-18 15:27 UTC
Probably originated from Ledger itself.
To reproduce: near send acc1.near acc2.near --useLedgerKey. Reproducable on both `near-cli 1.6.0` and `near-cli 2.0.0`. 
The transaction is successfully executed, the error occurs after it.
![image](https://user-images.githubusercontent.com/4030422/118679407-896f0100-b806-11eb-816a-460b3223302d.png)

**Comment by gonta71** [comment] 2021-05-24 23:56
Also related to #758.

**Comment by nagisa** [comment] 2022-01-16 14:50
I believe this and #758 are the same issue, so closing this as a duplicate of it.

**Closed by nagisa** 2022-01-16 14:50 UTC
Labels: bug, P2
